# Numpy
1. NumPy is a Python library used for working with arrays.
2. 
It also has functions for working in domain of linear algebra, fourier transfor and matrices.
3. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
4. NumPy stands for Numerical Python.
5. In Python we have lists that serve the purpose of arrays, but they are slow to process. 
NumPy aims to provide an array object that is up to 50x faster than traditional Python list
6. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
7. Arrays are very frequently used in data science, where speed and resources are very important.
8. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. 
This behavior is called locality of reference in computer scien.This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.
9. NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.res.s.ython.

In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

# Creating an array using numpy
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.


In [4]:

a = np.array([1,2,4,56,64,232,43]) #the argument can be a list/another array/tuple like sequence objects

print(a)
print(type(a))

[  1   2   4  56  64 232  43]
<class 'numpy.ndarray'>


# Dimensions in Arrays
1. 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
2. An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic array.  
3. An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensor.   
4. An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.   
5. NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.     
6. An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.
7. The shape attribute of a NumPy array returns a tuple representing the dimensions of the array. Each number in the tuple indicates the size of the array along that dimension.For example, if you have a 2D array with 2 rows and 3 columns, the shape of the array will be (2,3). Here, 2 is the number of rows and 3 is the number of columns.You can get the shape of a NumPy array arr by using arr.shape.

In [25]:
# Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)

42
0
1
()


In [29]:
# Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape) 
# The example above returns (5,), which means that the array has 1 dimensions, where the lone dimension has 5 elements.
# For a one-dimensional array, shape is still represented as a tuple with one element rather than an integer value. Note that a tuple with a single element has a trailing comma.

[1 2 3 4 5]
1
5
(5,)


In [30]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)
# The example above returns (2, 3), which means that the array has 2 dimensions, with each dimension having 3 elements.

[[1 2 3]
 [4 5 6]]
2
6
(2, 3)


In [31]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6,5,664,32:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6, 5, 664, 32]])

print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)
# The example above returns (2, 3), which means that the array has 2 dimensions, with each dimension having 3 elements.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [37]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3, 4], [4, 5, 6, 0]], [[1, 2, 3, 2], [4, 5, 6, 7]], [[1, 5, 8, 2], [3, 9, 6, 12]]])

print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)

'''
In this case, arr.shape will return (3, 2, 4). Here, 3 is the number of 2D arrays, 2 is the number of rows in each 2D array, and 4 is the number of columns in each 2D array.
So, the shape (3, 2, 4) means that there are 3 groups (or 2D arrays), each containing 2 rows and 4 columns.
'''

[[[ 1  2  3  4]
  [ 4  5  6  0]]

 [[ 1  2  3  2]
  [ 4  5  6  7]]

 [[ 1  5  8  2]
  [ 3  9  6 12]]]
3
24
(3, 2, 4)


'\nIn this case, arr.shape will return (3, 2, 4). Here, 3 is the number of 2D arrays, 2 is the number of rows in each 2D array, and 4 is the number of columns in each 2D array.\nSo, the shape (3, 2, 4) means that there are 3 groups (or 2D arrays), each containing 2 rows and 4 columns.\n'

In [34]:
# Create a 5-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], ndmin = 5)

print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)


'''
In this case, arr.shape will return (1, 1, 2, 2, 3). Here, 1, 1 are the two singleton dimensions added due to ndmin=5, 2 is the number of 2D arrays, 2 is the number of rows in each 2D array, and 3 is the number of columns in each 2D array.
So, the shape (1, 1, 2, 2, 3) means that there are 2 groups (or 2D arrays), each containing 2 rows and 3 columns, and these are nested within two singleton dimensions.
'''

[[[[[1 2 3]
    [4 5 6]]

   [[1 2 3]
    [4 5 6]]]]]
5
12
(1, 1, 2, 2, 3)


'\nIn this case, arr.shape will return (1, 1, 2, 2, 3). Here, 1, 1 are the two singleton dimensions added due to ndmin=5, 2 is the number of 2D arrays, 2 is the number of rows in each 2D array, and 3 is the number of columns in each 2D array.\nSo, the shape (1, 1, 2, 2, 3) means that there are 2 groups (or 2D arrays), each containing 2 rows and 3 columns, and these are nested within two singleton dimensions.\n'

# The numpy.ones() function returns a new array of given shape and type, with ones.

In [43]:
import numpy as np

array1 = np.ones((4,6))
array1
# Default datatype is float.




array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [42]:
array2 = np.ones((4,6), int) # specifically gave int as argument for dtype
array2
# Datatype is integer now for the ones inside the array.

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [53]:
import numpy as np

array1 = np.ones((4,6), str)
array1
# Each '1' in the array is a string representation of one.

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

# The numpy.zeroes() function returns a new array of given shape and type, with zeroes.¶

In [46]:
import numpy as np

array1 = np.zeros((4,6))
array1
# Default datatype is float.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [49]:
import numpy as np

array1 = np.zeros((4,6), int)
array1
# Datatype is integer now for the zeroes inside the array.

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [51]:
import numpy as np

array1 = np.zeros((4,6), str)
array1
# Each '' in the array is a zero-length string, which is the string equivalent of zero..

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

# numpy.empty_like() in Python

In [58]:
import numpy as np

arr = np.array([[[1, 2, 3, 4], [4, 5, 6, 0]], [[1, 2, 3, 2], [4, 5, 6, 7]], [[1, 5, 8, 2], [3, 9, 6, 12]]])


arr2 = np.empty_like(arr, int)
arr2
# In this code, arr2 is a new array with the same shape and type as a, but filled with uninitialized data.

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  0]],

       [[ 1,  2,  3,  2],
        [ 4,  5,  6,  7]],

       [[ 1,  5,  8,  2],
        [ 3,  9,  6, 12]]])

In [61]:
import numpy as np

arr = np.array([[[1, 2, 3, 4], [4, 5, 6, 0]], [[1, 2, 3, 2], [4, 5, 6, 7]], [[1, 5, 8, 2], [3, 9, 6, 12]]])


arr2 = np.zeros_like(arr, int)
print(arr2)

print()
print('*************************************************')
print()

arr3 = np.ones_like(arr, int)
print(arr3)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]

*************************************************

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


# NumPy Array Indexing
1. Array indexing is the same as accessing an array element.
2. You can access an array element by referring to its index number.
3. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.
4. Similar to lists, concept of negative indexing is also applicable to numpy arrays.

In [72]:
# Access 1-D array

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])
print(arr[-3]) # accessing same element using negative indexing

2
2


# Access 2-D Arrays :
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [77]:
# Access the element on the first row, second column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print()

print('2nd element on 1st row: ', arr[0, 1])
print('2nd element on 1st row: ', arr[-2, -4]) # accessing same element using negative indexing
print('2nd element on 1st row: ', arr[-2, 1]) # accessing same element using negative indexing
print('2nd element on 1st row: ', arr[0, -4]) # accessing same element using negative indexing


print()

print('4th element on 2nd row: ', arr[1, 3])
print('4th element on 2nd row: ', arr[-1, -2]) # accessing same element using negative indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

2nd element on 1st row:  2
2nd element on 1st row:  2
2nd element on 1st row:  2
2nd element on 1st row:  2

4th element on 2nd row:  9
4th element on 2nd row:  9


# Access 3-D Arrays :
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [79]:
# Access the fourth element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3, 383], [4, 5, 6, 4383]], [[7, 8, 9,843], [10, 11, 12,324]]])

print(arr)
print()

print(arr[0, 1, 3]) #  Access the fourth element of the second array of the first array
print(arr[-2, -1, -1]) # accessing same element using negative indexing


print()

print(arr[1, 0, 1]) #  Access the second element of the first array of the second array
print(arr[-1, -2, -3]) # accessing same element using negative indexing

[[[   1    2    3  383]
  [   4    5    6 4383]]

 [[   7    8    9  843]
  [  10   11   12  324]]]

4383
4383

8
8


# NumPy Array Slicing

In [86]:
# Slicing 1-D array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[:4])
print(arr[3:])
print(arr[-3:-1])
print(arr[: :3])
print(arr[1:5:2])

[2 3 4 5]
[1 2 3 4]
[4 5 6 7]
[5 6]
[1 4 7]
[2 4]


In [89]:
# Slicing 2-D array

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) #From the second element, slice elements from index 1 to index 4 (not included)

print(arr[0, :4]) #From the first element, slice elements from index 0 to index 4 (not included)

[7 8 9]
[1 2 3 4]


In [90]:
# Return elements at same index from multiple array elements

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [94]:
#From all array elements, slice index 1 to index 4 (not included), this will return a 2-D array

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

print(arr[0:, 1:4]) # Slicing elements from index 1 to 4(not included) for the arrays with index from 0 till end.

print()

print(arr[0:2, 0:3]) # Slicing elements from index 0 to 3(not included) for the arrays with index from 0 to 2.

# First slicing is for the outermost dimension arrays. Then next for arrays(one dimension inside) within those outermost dimension arrays and so on.

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

[[1 2 3]
 [6 7 8]]


# Data Types in NumPy

In [99]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)


arr1 = np.array([1, 2, 3, 4], dtype = 'S')
print(arr1.dtype)


arr1 = np.array([1, 2, 3, 4], dtype = 'i')
print(arr1.dtype)

<U6
|S1
int32


# Converting Data Type on Existing Arrays

In [106]:
# Change data type from float to integer by using 'i' or 'int' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr1 = arr.astype('i')
newarr2 = arr.astype('int')

print(arr)
print(arr.dtype)

print()

print(newarr1)
print(newarr1.dtype)

print()

print(newarr2)
print(newarr2.dtype)

# Many other similar kind of conversions are also possible between compatible datatypes.

[1.1 2.1 3.1]
float64

[1 2 3]
int32

[1 2 3]
int32


# Reshaping the arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [107]:
# Reshape From 1-D to 2-D
# Convert the following 1-D array with 12 elements into a 2-D array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
# The outermost dimension will have 4 arrays, each with 3 elements.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [108]:
# Reshape From 1-D to 3-D
# Convert the following 1-D array with 12 elements into a 3-D array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements.

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [240]:
# Reshaping a 2-D array into another 2-D array

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

print(arr)
print()
print(arr.shape)
print()


newarr = arr.reshape((5,3)) # this can also be written as newarr = np.reshape(arr, (5,3))
print(newarr)

newarr = np.reshape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

(3, 5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


# Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

# Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [115]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

newarr = arr.reshape(2, -1)
print(newarr)

print()

newarr1 = arr.reshape(2, 3, -1)
print(newarr1)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


# Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [118]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

newarr = arr.reshape(2, -1)
print(newarr)

print()

newarr1 = arr.reshape(2, 3, -1)
print(newarr1)

print('*****************************************************************************')

# Flattening the arrays to 1-D 
flat_arr1 = newarr.reshape(-1)
print(flat_arr1)

print()

flat_arr2 = newarr1.reshape(-1)
print(flat_arr2)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
*****************************************************************************
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


# NumPy Array Iterating

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [119]:
# Iterate on the elements of the following 1-D array

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [122]:
# Iterate on the elements of the following 2-D array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

print()

# To return the actual values, the scalars, we have to iterate the arrays in each dimension as below :

for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]

1
2
3
4
5
6


In [126]:
# Iterate on the elements of the following 3-D array

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr,'\n')
print()

for x in arr:
  print(x)

print()

# To return the actual values, the scalars, we have to iterate the arrays in each dimension as below :

for x in arr:
  for y in x:
    for z in y:
        print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()
1. The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration
2. In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality. nditer() is very helpful in such cases.

In [127]:
# Iterate through the following 3-D array

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [128]:
# Iterate through every scalar element of the 2D array skipping 1 element

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


# Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [129]:
# Enumerate on following 2D array's elements

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for index, x in np.ndenumerate(arr):
  print(index, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining NumPy Arrays
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [130]:
# Joining two 1-D arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [136]:
# Join two 2-D arrays along rows 
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # axis = 1 would mean number of rows would remain constant and new elements would be added within the same row elements

print(arr)
print('\n', arr.shape)

[[1 2 5 6]
 [3 4 7 8]]

 (2, 4)


In [135]:
# Join two 2-D arrays along columns 
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0) # axis = 1 would mean number of columns would remain constant and new elements would be added within the same column elements

print(arr)
print('\n', arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

 (4, 2)


# Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0

In [145]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])



arr_stacked_1 = np.stack((arr1, arr2), axis=1) # stacking along columns

arr_stacked_2 = np.stack((arr1, arr2, arr3), axis=1) # stacking along columns

print(arr_stacked_1)
print()
print(arr_stacked_2)



print()
print(np.stack((arr1, arr2, arr3), axis = 0)) # stacking along rows

[[1 4]
 [2 5]
 [3 6]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Stacking Along Rows :
NumPy provides a helper function: hstack() to stack along rows.

In [142]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.hstack((arr1, arr2))

print(arr)
print()
print(np.hstack((arr1, arr2, arr3)))

[1 2 3 4 5 6]

[1 2 3 4 5 6 7 8 9]


# Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [144]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.vstack((arr1, arr2))

print(arr)
print()
print(np.vstack((arr1, arr2, arr3)))

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.



In [146]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.dstack((arr1, arr2))

print(arr)
print()
print(np.dstack((arr1, arr2, arr3)))

[[[1 4]
  [2 5]
  [3 6]]]

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


# Splitting NumPy Arrays

1. We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
2. The return value of the array_split() method is an array containing each of the split as an array.
3. If you split an array into multiple arrays, you can access them from the result just like any array element

In [152]:
# Split the array in 3 parts

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print()
print(newarr[1])

print()


# If the array has less elements than required, it will adjust from the end accordingly.
newarr1 = np.array_split(arr, 4)

print(newarr1)
print()
print(newarr1[0])

[array([1, 2]), array([3, 4]), array([5, 6])]

[3 4]

[array([1, 2]), array([3, 4]), array([5]), array([6])]

[1 2]


In [157]:
# Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(arr)
print()

print(newarr)
print()
print(newarr[2])
print()



# If the array has less elements than required, it will adjust from the end accordingly.
newarr1 = np.array_split(arr, 5)
print(newarr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]

[[13 14 15]
 [16 17 18]]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]


In [160]:
# In addition, you can specify which axis you want to do the split around.
# The example below also returns three 2-D arrays, but they are split along the row (axis=1).

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

arr1 = np.array([[1, 2, 3, 100], [4, 5, 6, 99], [7, 8, 9, 98], [10, 11, 12, 97], [13, 14, 15, 97], [16, 17, 18, 96]])


newarr = np.array_split(arr, 3, axis=1)
newarr1 = np.array_split(arr1, 3, axis=1)

print(newarr)
print()
print(newarr1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([[100],
       [ 99],
       [ 98],
       [ 97],
       [ 97],
       [ 96]])]


# Similar alternates to hstack(), vstack() and dstack() are available as hsplit(), vsplit() and dsplit().

In [165]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])


print(np.hsplit(arr, 3))
print()
print(np.vsplit(arr, 3))
print()
print(np.dsplit(arr, 3))

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]



ValueError: dsplit only works on arrays of 3 or more dimensions

# NumPy Searching Arrays
We can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [170]:
# Find the indexes where the value is 4

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)
print(type(x))
print(x[0])
print(x[0][2])

(array([3, 5, 6], dtype=int64),)
<class 'tuple'>
[3 5 6]
6


In [175]:
# Find the indexes where the values are even.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)
print()


# We can even use them to get all even elements as below
for i in x:
    print(arr[i])

(array([1, 3, 5, 7], dtype=int64),)

[2 4 6 8]


# Sorting Arrays
1. The NumPy ndarray object has a function called sort(), that will sort a specified array.
2. This method returns a copy of the array, leaving the original array unchanged.


In [246]:
import numpy as np

arr = np.array([3, 2, 0, 1])
arr1 = np.array(['banana', 'cherry', 'apple'])

# Ascending sort
print(np.sort(arr))
print(np.sort(arr1))

# Descending sort through the use of negative indexing
print(np.sort(arr)[::-1]) 
print(np.sort(arr1)[::-1])

[0 1 2 3]
['apple' 'banana' 'cherry']
[3 2 1 0]
['cherry' 'banana' 'apple']


In [181]:
# If you use the sort() method on a 2-D array, both arrays will be sorted:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1], [4, 67, 45], [34, 3, 89]])

print(arr.ndim)
print(np.sort(arr))

2
[[ 2  3  4]
 [ 0  1  5]
 [ 4 45 67]
 [ 3 34 89]]


# NumPy Filter Array
1. In NumPy, you filter an array using a boolean index list.
2. A boolean index list is a list of booleans corresponding to indexes in the array.
3. If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [183]:
# Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False] # boolean index list also called as filter array

newarr = arr[x]

print(newarr)

# The new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

[41 43]


In [185]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44, 2, 32, 69, 90])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True, False, False, True, True]
[43 44 69 90]


In [186]:
# Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 34, 45, 232, 433, 47, 89, 440])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False, True, False, False, False, True]
[  2   4   6  34 232 440]


In [187]:
# Creating Filter Directly From Array
# We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 34, 45, 232, 433, 47, 89, 440])

filter_arr = (arr % 2 == 0)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False  True False  True False False
 False  True]
[  2   4   6  34 232 440]


# Same object can also be achieved using where() method.

In [189]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44, 2, 32, 69, 90])

x = np.where(arr >  42)

print(arr[x])


[43 44 69 90]


In [190]:
# Create a filter array that will return only even elements from the original array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 34, 45, 232, 433, 47, 89, 440])

x = np.where(arr % 2 == 0)

print(arr[x])

[  2   4   6  34 232 440]


# Simple Arithmetic on numpy arrays
1. You could use arithmetic operators + - * / directly between NumPy arrays

In [241]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr)
print()

print(arr * 5) # Multiplying array by 5 multiplies all nos inside array by 5. This phenomenon is better known as broadcasting wherein same operation is performed on all elements of the array.
print()

print(arr - 10) # Substracting array by 10 substracts all nos inside array by 10.
print()

print(arr + 10) # Adding array by 10 adds all nos inside array by 10.
print()

print(arr / 10) # Dividing array by 10 divides all nos inside array by 10.
print()

print(arr % 2) # Gives remainder left after each number from array is divided by 2.
print()

print(arr ** 3) # Gives array of cubic powers of all nos inside the original array
print()

# Resultant in all above cases is again a new array.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]
 [65 70 75]
 [80 85 90]]

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]
 [26 27 28]]

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [1.  1.1 1.2]
 [1.3 1.4 1.5]
 [1.6 1.7 1.8]]

[[1 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 0]]

[[   1    8   27]
 [  64  125  216]
 [ 343  512  729]
 [1000 1331 1728]
 [2197 2744 3375]
 [4096 4913 5832]]



In [218]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

print('addition = ', np.add(arr1, arr2)) # arr1 + arr2 >> (corresponding elements) >> This phenomenon of element-wise operations is called vectorization
print('addition = ', arr1 + arr2)
print()

print('subtraction = ', np.subtract(arr1, arr2)) # arr1 - arr2 >> (corresponding elements)
print('subtraction = ', arr1 - arr2)
print()

print('Product = ', np.multiply(arr1, arr2)) # arr1 * arr2 >> (corresponding elements)
print('Product = ', arr1 * arr2)
print()

print('Division = ', np.divide(arr1, arr2)) # arr1 / arr2 >> (corresponding elements)
print('Division = ', arr1 / arr2)
print('Floor Division = ', arr1 // arr2)
print()

print('Remainder = ', np.mod(arr1, arr2)) # arr1 % arr2 >> (corresponding elements)
print('Remainder = ', np.remainder(arr1, arr2)) # arr1 - arr2 >> (corresponding elements)
print('Remainder = ', arr1 % arr2)
print()

print('Power = ', np.power(arr1, arr2)) #The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.
print('Power = ', arr1 ** arr2)
print()



print('Divmod = ', np.divmod(arr1, arr2)) # divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.



arr = np.array([-1, -2, 1, 2, 3, -4, -100, -23433])

print('absolute value = ', np.absolute(arr)) # getting absolute value


addition =  [13 25 36 48 52 93]
addition =  [13 25 36 48 52 93]

subtraction =  [ 7 15 24 32 48 27]
subtraction =  [ 7 15 24 32 48 27]

Product =  [  30  100  180  320  100 1980]
Product =  [  30  100  180  320  100 1980]

Division =  [ 3.33333333  4.          5.          5.         25.          1.81818182]
Division =  [ 3.33333333  4.          5.          5.         25.          1.81818182]
Floor Division =  [ 3  4  5  5 25  1]

Remainder =  [ 1  0  0  0  0 27]
Remainder =  [ 1  0  0  0  0 27]

Power =  [      1000    3200000  729000000 -520093696       2500          0]
Power =  [      1000    3200000  729000000 -520093696       2500          0]

Remainder =  [ 1  0  0  0  0 27]
Divmod =  (array([ 3,  4,  5,  5, 25,  1]), array([ 1,  0,  0,  0,  0, 27]))
absolute value =  [    1     2     1     2     3     4   100 23433]


# numpy.mean()

numpy.mean(arr, axis = None) : Compute the arithmetic mean (average) of the given data (array elements) along the specified axis.



In [222]:
arr1 = np.array([10, 20, 30, 40, 50, 60])

print(arr1.mean()) # Getting mean without use of numpy
print(np.mean(arr1)) # Getting mean with use of numpy

35.0
35.0


In [224]:


import numpy as np 
    
  
# 2D array  
arr = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4, ]]  
    
# mean of the flattened array  
print("\nmean of arr, axis = None : ", np.mean(arr))  # mean of all elements of array
    
# mean along the axis = 0  
print("\nmean of arr, axis = 0 : ", np.mean(arr, axis = 0))  # mean for each column
   
# mean along the axis = 1  
print("\nmean of arr, axis = 1 : ", np.mean(arr, axis = 1)) # mean for each row


mean of arr, axis = None :  18.6

mean of arr, axis = 0 :  [17.33333333  8.33333333 31.         14.         22.33333333]

mean of arr, axis = 1 :  [24.  15.  16.8]


# numpy.sum() in Python
numpy.sum(arr, axis, dtype, out) : This function returns the sum of array elements over the specified axis

In [225]:
import numpy as np 
      
# 2D array 
arr = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4,]]   
  
print("\nSum of arr : ", np.sum(arr)) # sum of all elements of array
  
print("Sum of arr(axis = 0) : ", np.sum(arr, axis = 0)) # column-wise sum
print("Sum of arr(axis = 1) : ", np.sum(arr, axis = 1)) # row-wise sum
 


Sum of arr :  279
Sum of arr(axis = 0) :  [52 25 93 42 67]
Sum of arr(axis = 1) :  [120  75  84]

Sum of arr (keepdimension is True): 
 [[120]
 [ 75]
 [ 84]]


# numpy.max(), numpy.min() in Python

In [231]:
import numpy as np 
      
# 2D array 
arr = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4,]]   
  
print("\nMax of arr : ", np.max(arr)) # max of all elements of array
print("Max of arr(axis = 0) : ", np.max(arr, axis = 0)) # max of nos for each column
print("Max of arr(axis = 1) : ", np.max(arr, axis = 1)) # max of nos for each row

print("\nMin of arr : ", np.max(arr)) # min of all elements of array
print("Min of arr(axis = 0) : ", np.max(arr, axis = 0)) # min of nos for each column
print("Min of arr(axis = 1) : ", np.max(arr, axis = 1)) # min of nos for each row



Max of arr :  54
Max of arr(axis = 0) :  [23 17 54 33 44]
Max of arr(axis = 1) :  [44 27 54]

Min of arr :  54
Min of arr(axis = 0) :  [23 17 54 33 44]
Min of arr(axis = 1) :  [44 27 54]
