In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('titanic.csv')
df

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0         3    male  22.0      1      0       1   7.2500   NaN        S   
1         1  female  38.0      1      0       1  71.2833   C85        C   
2         3  female  26.0      0      0       0   7.9250   NaN        S   
3         1  female  35.0      1      0       1  53.1000  C123        S   
4         3    male  35.0      0      0       0   8.0500   NaN        S   
..      ...     ...   ...    ...    ...     ...      ...   ...      ...   
886       2    male  27.0      0      0       0  13.0000   NaN        S   
887       1  female  19.0      0      0       0  30.0000   B42        S   
888       3  female   NaN      1      2       3  23.4500   NaN        S   
889       1    male  26.0      0      0       0  30.0000  C148        C   
890       3    male  32.0      0      0       0   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 10 columns]

In [3]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df

E:\spark_temp\ipykernel_17176\432742771.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)


Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0         3    male  22.0      1      0       1   7.2500   NaN        S   
1         1  female  38.0      1      0       1  71.2833   C85        C   
2         3  female  26.0      0      0       0   7.9250   NaN        S   
3         1  female  35.0      1      0       1  53.1000  C123        S   
4         3    male  35.0      0      0       0   8.0500   NaN        S   
..      ...     ...   ...    ...    ...     ...      ...   ...      ...   
886       2    male  27.0      0      0       0  13.0000   NaN        S   
887       1  female  19.0      0      0       0  30.0000   B42        S   
888       3  female  28.0      1      2       3  23.4500   NaN        S   
889       1    male  26.0      0      0       0  30.0000  C148        C   
890       3    male  32.0      0      0       0   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 10 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   family    891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object 
 8   Embarked  891 non-null    object 
 9   Survived  891 non-null    int64  
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB


In [5]:
df['Cabin'].fillna(0, inplace=True)
df.head(5)

E:\spark_temp\ipykernel_17176\2743770783.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna(0, inplace=True)


Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500     0        S   
1       1  female  38.0      1      0       1  71.2833   C85        C   
2       3  female  26.0      0      0       0   7.9250     0        S   
3       1  female  35.0      1      0       1  53.1000  C123        S   
4       3    male  35.0      0      0       0   8.0500     0        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [6]:
print(df[df['Cabin'] != 0])

     Pclass     Sex   Age  SibSp  Parch  family     Fare        Cabin  \
1         1  female  38.0      1      0       1  71.2833          C85   
3         1  female  35.0      1      0       1  53.1000         C123   
6         1    male  54.0      0      0       0  51.8625          E46   
10        3  female   4.0      1      1       2  16.7000           G6   
11        1  female  58.0      0      0       0  26.5500         C103   
..      ...     ...   ...    ...    ...     ...      ...          ...   
871       1  female  47.0      1      1       2  52.5542          D35   
872       1    male  33.0      0      0       0   5.0000  B51 B53 B55   
879       1  female  56.0      0      1       1  83.1583          C50   
887       1  female  19.0      0      0       0  30.0000          B42   
889       1    male  26.0      0      0       0  30.0000         C148   

    Embarked  Survived  
1          C         1  
3          S         1  
6          S         0  
10         S         1 

In [7]:
df['Cabin'][df['Cabin'] != 0] = 1
df

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0         3    male  22.0      1      0       1   7.2500     0        S   
1         1  female  38.0      1      0       1  71.2833     1        C   
2         3  female  26.0      0      0       0   7.9250     0        S   
3         1  female  35.0      1      0       1  53.1000     1        S   
4         3    male  35.0      0      0       0   8.0500     0        S   
..      ...     ...   ...    ...    ...     ...      ...   ...      ...   
886       2    male  27.0      0      0       0  13.0000     0        S   
887       1  female  19.0      0      0       0  30.0000     1        S   
888       3  female  28.0      1      2       3  23.4500     0        S   
889       1    male  26.0      0      0       0  30.0000     1        C   
890       3    male  32.0      0      0       0   7.7500     0        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 10 columns]

In [8]:
df = pd.get_dummies(df, columns = ['Sex','Embarked'], drop_first=True)
df

Pclass   Age  SibSp  Parch  family     Fare Cabin  Survived  Sex_male  \
0         3  22.0      1      0       1   7.2500     0         0      True   
1         1  38.0      1      0       1  71.2833     1         1     False   
2         3  26.0      0      0       0   7.9250     0         1     False   
3         1  35.0      1      0       1  53.1000     1         1     False   
4         3  35.0      0      0       0   8.0500     0         0      True   
..      ...   ...    ...    ...     ...      ...   ...       ...       ...   
886       2  27.0      0      0       0  13.0000     0         0      True   
887       1  19.0      0      0       0  30.0000     1         1     False   
888       3  28.0      1      2       3  23.4500     0         0     False   
889       1  26.0      0      0       0  30.0000     1         1      True   
890       3  32.0      0      0       0   7.7500     0         0      True   

     Embarked_N  Embarked_Q  Embarked_S  
0         False       False        True  
1         False       False       False  
2         False       False        True  
3         False       False        True  
4         False       False        True  
..          ...         ...         ...  
886       False       False        True  
887       False       False        True  
888       False       False        True  
889       False       False       False  
890       False        True       False  

[891 rows x 12 columns]

In [9]:
df['Sex_male']=df['Sex_male'].astype(int)
df['Embarked_N']=df['Embarked_N'].astype(int)
df['Embarked_Q']=df['Embarked_Q'].astype(int)
df['Embarked_S']=df['Embarked_S'].astype(int)
df.head()

Pclass   Age  SibSp  Parch  family     Fare Cabin  Survived  Sex_male  \
0       3  22.0      1      0       1   7.2500     0         0         1   
1       1  38.0      1      0       1  71.2833     1         1         0   
2       3  26.0      0      0       0   7.9250     0         1         0   
3       1  35.0      1      0       1  53.1000     1         1         0   
4       3  35.0      0      0       0   8.0500     0         0         1   

   Embarked_N  Embarked_Q  Embarked_S  
0           0           0           1  
1           0           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1

In [10]:
from sklearn.model_selection import train_test_split
X = df.loc[:,df.columns!= 'Survived']
y = df['Survived']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [11]:
from sklearn.linear_model import LogisticRegression
m1 = LogisticRegression()
m1.fit(X_train,y_train)

C:\Users\Tejas Patil\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
pred =m1.predict(X_test)
pred

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0], dtype=int64)

In [13]:
m1.predict_proba(X_test)

array([[0.08707332, 0.91292668],
       [0.92240291, 0.07759709],
       [0.16348004, 0.83651996],
       [0.29277578, 0.70722422],
       [0.09149344, 0.90850656],
       [0.89824667, 0.10175333],
       [0.6314166 , 0.3685834 ],
       [0.08625204, 0.91374796],
       [0.72972963, 0.27027037],
       [0.40644622, 0.59355378],
       [0.91277209, 0.08722791],
       [0.40155253, 0.59844747],
       [0.6781783 , 0.3218217 ],
       [0.83607654, 0.16392346],
       [0.29261857, 0.70738143],
       [0.39912604, 0.60087396],
       [0.95013804, 0.04986196],
       [0.94323412, 0.05676588],
       [0.94350377, 0.05649623],
       [0.32200994, 0.67799006],
       [0.93373288, 0.06626712],
       [0.92328382, 0.07671618],
       [0.02347757, 0.97652243],
       [0.78966589, 0.21033411],
       [0.31208166, 0.68791834],
       [0.91941743, 0.08058257],
       [0.06125574, 0.93874426],
       [0.36233573, 0.63766427],
       [0.82338153, 0.17661847],
       [0.11922408, 0.88077592],
       [0.

In [14]:
from sklearn.metrics import confusion_matrix
labels = np.unique(y_test)
cm = confusion_matrix(y_test, pred, labels = labels)

In [15]:
cm

array([[132,  21],
       [ 34,  81]], dtype=int64)

In [16]:
from sklearn import metrics

accuracy = metrics.accuracy_score(y_test, pred)
Precision = metrics.precision_score(y_test, pred)
Recall = metrics.recall_score(y_test, pred)

print("Accuracy:", accuracy)
print("Precision:", Precision)
print("Recall:", Recall)

Accuracy: 0.7947761194029851
Precision: 0.7941176470588235
Recall: 0.7043478260869566
