In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Titanic.csv')
df.head()

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500   NaN        S   
1       1  female  38.0      1      0       1  71.2833   C85        C   
2       3  female  26.0      0      0       0   7.9250   NaN        S   
3       1  female  35.0      1      0       1  53.1000  C123        S   
4       3    male  35.0      0      0       0   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df['Age'].fillna (df['Age'].mean(), inplace=True) 

In [4]:
df.head()

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500   NaN        S   
1       1  female  38.0      1      0       1  71.2833   C85        C   
2       3  female  26.0      0      0       0   7.9250   NaN        S   
3       1  female  35.0      1      0       1  53.1000  C123        S   
4       3    male  35.0      0      0       0   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [5]:
df['Cabin'].fillna(0,inplace=True)

In [6]:
df.head()

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500     0        S   
1       1  female  38.0      1      0       1  71.2833   C85        C   
2       3  female  26.0      0      0       0   7.9250     0        S   
3       1  female  35.0      1      0       1  53.1000  C123        S   
4       3    male  35.0      0      0       0   8.0500     0        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [7]:
df['Cabin'] [df['Cabin'] !=0] = 1

In [8]:
df.head()

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500     0        S   
1       1  female  38.0      1      0       1  71.2833     1        C   
2       3  female  26.0      0      0       0   7.9250     0        S   
3       1  female  35.0      1      0       1  53.1000     1        S   
4       3    male  35.0      0      0       0   8.0500     0        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [9]:
df= pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

In [10]:
df.head()

Pclass   Age  SibSp  Parch  family     Fare Cabin  Survived  Sex_male  \
0       3  22.0      1      0       1   7.2500     0         0      True   
1       1  38.0      1      0       1  71.2833     1         1     False   
2       3  26.0      0      0       0   7.9250     0         1     False   
3       1  35.0      1      0       1  53.1000     1         1     False   
4       3  35.0      0      0       0   8.0500     0         0      True   

   Embarked_N  Embarked_Q  Embarked_S  
0       False       False        True  
1       False       False       False  
2       False       False        True  
3       False       False        True  
4       False       False        True

In [11]:
df['Sex_male'] = df['Sex_male'].astype(int)
df['Embarked_N'] = df['Embarked_N'].astype (int)
df['Embarked_Q'] = df['Embarked_Q'].astype (int)
df['Embarked_S'] = df['Embarked_S'].astype (int)
df.head()

Pclass   Age  SibSp  Parch  family     Fare Cabin  Survived  Sex_male  \
0       3  22.0      1      0       1   7.2500     0         0         1   
1       1  38.0      1      0       1  71.2833     1         1         0   
2       3  26.0      0      0       0   7.9250     0         1         0   
3       1  35.0      1      0       1  53.1000     1         1         0   
4       3  35.0      0      0       0   8.0500     0         0         1   

   Embarked_N  Embarked_Q  Embarked_S  
0           0           0           1  
1           0           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1

In [12]:
df.corr()

Pclass       Age     SibSp     Parch    family      Fare  \
Pclass      1.000000 -0.331339  0.083081  0.018443  0.065997 -0.549500   
Age        -0.331339  1.000000 -0.232625 -0.179191 -0.248512  0.091566   
SibSp       0.083081 -0.232625  1.000000  0.414838  0.890712  0.159651   
Parch       0.018443 -0.179191  0.414838  1.000000  0.783111  0.216225   
family      0.065997 -0.248512  0.890712  0.783111  1.000000  0.217138   
Fare       -0.549500  0.091566  0.159651  0.216225  0.217138  1.000000   
Cabin      -0.725541  0.233123 -0.040460  0.036987 -0.009175  0.482075   
Survived   -0.338481 -0.069809 -0.035322  0.081629  0.016639  0.257307   
Sex_male    0.131900  0.084153 -0.114631 -0.245489 -0.200988 -0.182333   
Embarked_N -0.074282  0.074099 -0.022508 -0.022467 -0.026608  0.045646   
Embarked_Q  0.221009 -0.013855 -0.026354 -0.081228 -0.058592 -0.117216   
Embarked_S  0.081720 -0.027121  0.070941  0.063036  0.079977 -0.166603   

               Cabin  Survived  Sex_male  Embarked_N  Embarked_Q  Embarked_S  
Pclass     -0.725541 -0.338481  0.131900   -0.074282    0.221009    0.081720  
Age         0.233123 -0.069809  0.084153    0.074099   -0.013855   -0.027121  
SibSp      -0.040460 -0.035322 -0.114631   -0.022508   -0.026354    0.070941  
Parch       0.036987  0.081629 -0.245489   -0.022467   -0.081228    0.063036  
family     -0.009175  0.016639 -0.200988   -0.026608   -0.058592    0.079977  
Fare        0.482075  0.257307 -0.182333    0.045646   -0.117216   -0.166603  
Cabin       1.000000  0.316912 -0.140391    0.087042   -0.129572   -0.110087  
Survived    0.316912  1.000000 -0.543351    0.060095    0.003650   -0.155660  
Sex_male   -0.140391 -0.543351  1.000000   -0.064296   -0.074115    0.125722  
Embarked_N  0.087042  0.060095 -0.064296    1.000000   -0.014588   -0.076588  
Embarked_Q -0.129572  0.003650 -0.074115   -0.014588    1.000000   -0.496624  
Embarked_S -0.110087 -0.155660  0.125722   -0.076588   -0.496624    1.000000

In [13]:
from sklearn.model_selection import train_test_split
X=df.loc[:, df.columns != 'Survived']
y=df ['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [14]:
from sklearn.linear_model import LogisticRegression
m1 = LogisticRegression()
m1.fit(X_train, y_train)

C:\Users\Tejas Patil\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
pred = m1.predict(X_test)
pred

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0], dtype=int64)

In [16]:
m1.predict_proba(X_test)

array([[0.11756682, 0.88243318],
       [0.92139706, 0.07860294],
       [0.18104897, 0.81895103],
       [0.26514211, 0.73485789],
       [0.11512368, 0.88487632],
       [0.89131964, 0.10868036],
       [0.69547393, 0.30452607],
       [0.09846694, 0.90153306],
       [0.65121361, 0.34878639],
       [0.32986489, 0.67013511],
       [0.90623964, 0.09376036],
       [0.41350455, 0.58649545],
       [0.71539614, 0.28460386],
       [0.84215198, 0.15784802],
       [0.26504914, 0.73495086],
       [0.45590116, 0.54409884],
       [0.92004707, 0.07995293],
       [0.9268418 , 0.0731582 ],
       [0.93820593, 0.06179407],
       [0.30636432, 0.69363568],
       [0.92797421, 0.07202579],
       [0.88551775, 0.11448225],
       [0.02804659, 0.97195341],
       [0.78049177, 0.21950823],
       [0.25246213, 0.74753787],
       [0.91306252, 0.08693748],
       [0.05009779, 0.94990221],
       [0.38229626, 0.61770374],
       [0.82044763, 0.17955237],
       [0.12744807, 0.87255193],
       [0.

In [17]:
from sklearn.metrics import confusion_matrix
labels = np.unique(y_test)
cm = confusion_matrix(y_test, pred, labels = labels)

In [18]:
cm

array([[128,  25],
       [ 32,  83]], dtype=int64)

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.80      0.84      0.82       153
           1       0.77      0.72      0.74       115

    accuracy                           0.79       268
   macro avg       0.78      0.78      0.78       268
weighted avg       0.79      0.79      0.79       268



In [20]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, pred)
Precision = metrics.precision_score(y_test, pred)
Recall = metrics.recall_score(y_test, pred)
print("Accuracy :",accuracy)
print("Precision:",Precision)
print("Recall   :",Recall)

Accuracy : 0.7873134328358209
Precision: 0.7685185185185185
Recall   : 0.7217391304347827
