In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Titanic.csv')
df.head()

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500   NaN        S   
1       1  female  38.0      1      0       1  71.2833   C85        C   
2       3  female  26.0      0      0       0   7.9250   NaN        S   
3       1  female  35.0      1      0       1  53.1000  C123        S   
4       3    male  35.0      0      0       0   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df['Age'].fillna (df['Age'].mean(), inplace=True) 

In [4]:
df.head()

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500   NaN        S   
1       1  female  38.0      1      0       1  71.2833   C85        C   
2       3  female  26.0      0      0       0   7.9250   NaN        S   
3       1  female  35.0      1      0       1  53.1000  C123        S   
4       3    male  35.0      0      0       0   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [5]:
df['Cabin'].fillna(0,inplace=True)

In [6]:
df.head()

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500     0        S   
1       1  female  38.0      1      0       1  71.2833   C85        C   
2       3  female  26.0      0      0       0   7.9250     0        S   
3       1  female  35.0      1      0       1  53.1000  C123        S   
4       3    male  35.0      0      0       0   8.0500     0        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [7]:
df['Cabin'] [df['Cabin'] !=0] = 1

In [8]:
df.head()

Pclass     Sex   Age  SibSp  Parch  family     Fare Cabin Embarked  \
0       3    male  22.0      1      0       1   7.2500     0        S   
1       1  female  38.0      1      0       1  71.2833     1        C   
2       3  female  26.0      0      0       0   7.9250     0        S   
3       1  female  35.0      1      0       1  53.1000     1        S   
4       3    male  35.0      0      0       0   8.0500     0        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [9]:
df= pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

In [10]:
df.head()

Pclass   Age  SibSp  Parch  family     Fare Cabin  Survived  Sex_male  \
0       3  22.0      1      0       1   7.2500     0         0      True   
1       1  38.0      1      0       1  71.2833     1         1     False   
2       3  26.0      0      0       0   7.9250     0         1     False   
3       1  35.0      1      0       1  53.1000     1         1     False   
4       3  35.0      0      0       0   8.0500     0         0      True   

   Embarked_N  Embarked_Q  Embarked_S  
0       False       False        True  
1       False       False       False  
2       False       False        True  
3       False       False        True  
4       False       False        True

In [11]:
df['Sex_male'] = df['Sex_male'].astype(int)
df['Embarked_N'] = df['Embarked_N'].astype (int)
df['Embarked_Q'] = df['Embarked_Q'].astype (int)
df['Embarked_S'] = df['Embarked_S'].astype (int)
df.head()

Pclass   Age  SibSp  Parch  family     Fare Cabin  Survived  Sex_male  \
0       3  22.0      1      0       1   7.2500     0         0         1   
1       1  38.0      1      0       1  71.2833     1         1         0   
2       3  26.0      0      0       0   7.9250     0         1         0   
3       1  35.0      1      0       1  53.1000     1         1         0   
4       3  35.0      0      0       0   8.0500     0         0         1   

   Embarked_N  Embarked_Q  Embarked_S  
0           0           0           1  
1           0           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1

In [12]:
df.corr()

Pclass       Age     SibSp     Parch    family      Fare  \
Pclass      1.000000 -0.331339  0.083081  0.018443  0.065997 -0.549500   
Age        -0.331339  1.000000 -0.232625 -0.179191 -0.248512  0.091566   
SibSp       0.083081 -0.232625  1.000000  0.414838  0.890712  0.159651   
Parch       0.018443 -0.179191  0.414838  1.000000  0.783111  0.216225   
family      0.065997 -0.248512  0.890712  0.783111  1.000000  0.217138   
Fare       -0.549500  0.091566  0.159651  0.216225  0.217138  1.000000   
Cabin      -0.725541  0.233123 -0.040460  0.036987 -0.009175  0.482075   
Survived   -0.338481 -0.069809 -0.035322  0.081629  0.016639  0.257307   
Sex_male    0.131900  0.084153 -0.114631 -0.245489 -0.200988 -0.182333   
Embarked_N -0.074282  0.074099 -0.022508 -0.022467 -0.026608  0.045646   
Embarked_Q  0.221009 -0.013855 -0.026354 -0.081228 -0.058592 -0.117216   
Embarked_S  0.081720 -0.027121  0.070941  0.063036  0.079977 -0.166603   

               Cabin  Survived  Sex_male  Embarked_N  Embarked_Q  Embarked_S  
Pclass     -0.725541 -0.338481  0.131900   -0.074282    0.221009    0.081720  
Age         0.233123 -0.069809  0.084153    0.074099   -0.013855   -0.027121  
SibSp      -0.040460 -0.035322 -0.114631   -0.022508   -0.026354    0.070941  
Parch       0.036987  0.081629 -0.245489   -0.022467   -0.081228    0.063036  
family     -0.009175  0.016639 -0.200988   -0.026608   -0.058592    0.079977  
Fare        0.482075  0.257307 -0.182333    0.045646   -0.117216   -0.166603  
Cabin       1.000000  0.316912 -0.140391    0.087042   -0.129572   -0.110087  
Survived    0.316912  1.000000 -0.543351    0.060095    0.003650   -0.155660  
Sex_male   -0.140391 -0.543351  1.000000   -0.064296   -0.074115    0.125722  
Embarked_N  0.087042  0.060095 -0.064296    1.000000   -0.014588   -0.076588  
Embarked_Q -0.129572  0.003650 -0.074115   -0.014588    1.000000   -0.496624  
Embarked_S -0.110087 -0.155660  0.125722   -0.076588   -0.496624    1.000000

In [13]:
from sklearn.model_selection import train_test_split
X=df.loc[:, df.columns != 'Survived']
y=df ['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [15]:
from sklearn.naive_bayes import GaussianNB
m2 = GaussianNB()
m2.fit(X, y)

GaussianNB()

In [16]:
pred = m2.predict(X_test)
pred

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0], dtype=int64)

In [17]:
m2.predict_proba(X_test)

array([[2.19176251e-01, 7.80823749e-01],
       [9.99469072e-01, 5.30927805e-04],
       [9.47127139e-01, 5.28728613e-02],
       [9.39094820e-01, 6.09051796e-02],
       [9.13949571e-01, 8.60504287e-02],
       [9.99390863e-01, 6.09137289e-04],
       [9.72162081e-01, 2.78379188e-02],
       [1.32543446e-01, 8.67456554e-01],
       [9.23502579e-01, 7.64974207e-02],
       [9.33312142e-01, 6.66878575e-02],
       [9.99434469e-01, 5.65531484e-04],
       [9.79280650e-01, 2.07193500e-02],
       [8.56123477e-01, 1.43876523e-01],
       [9.98840303e-01, 1.15969685e-03],
       [9.38978012e-01, 6.10219878e-02],
       [9.12212819e-01, 8.77871808e-02],
       [9.99999473e-01, 5.27173758e-07],
       [9.99366879e-01, 6.33121041e-04],
       [9.99492029e-01, 5.07970710e-04],
       [9.99585130e-01, 4.14869964e-04],
       [9.99480453e-01, 5.19547139e-04],
       [9.98291323e-01, 1.70867722e-03],
       [5.68605133e-02, 9.43139487e-01],
       [9.94419525e-01, 5.58047477e-03],
       [9.229525

In [18]:
from sklearn.metrics import confusion_matrix
labels = np.unique(y_test)
cm = confusion_matrix(y_test, pred, labels = labels)

In [19]:
cm

array([[148,   5],
       [ 80,  35]], dtype=int64)

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.65      0.97      0.78       153
           1       0.88      0.30      0.45       115

    accuracy                           0.68       268
   macro avg       0.76      0.64      0.61       268
weighted avg       0.75      0.68      0.64       268



In [21]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, pred)
Precision = metrics.precision_score(y_test, pred)
Recall = metrics.recall_score(y_test, pred)
print("Accuracy :",accuracy)
print("Precision:",Precision)
print("Recall   :",Recall)

Accuracy : 0.6828358208955224
Precision: 0.875
Recall   : 0.30434782608695654
